weights_person: #yolo_person
  weights: '/weight/crowdhuman_yolov5m.pt'
  classes: 0
  device: 0
  iou_thres: 0.4
  conf_thres: 0.7
  img_size: 640
  max_det: 1000
  agnostic_nms: False
#yolo_FS
weights_FS:
  weights: '/weight/fire_smoke/fire_smoke.pt'
  classes: null
  device: 0
  iou_thres: 0.4
  conf_thres: 0.5
  img_size: 640
  max_det: 1000
  agnostic_nms: False
#yolo_hat
weights_hat:
  weights: '/weight/Hat/best_Hat.pt'
  classes: null
  device: 0
  iou_thres: 0.4
  conf_thres: 0.5
  img_size: 640
  max_det: 1000
  agnostic_nms: False
#yolo_vehicle
weights_vehicle:
  weights: '/weight/vehicle/only_vehical_150epoch.pt'
  classes: null
  device: 0
  iou_thres: 0.4
  conf_thres: 0.5
  img_size: 640
  max_det: 1000
  agnostic_nms: False

#yolo_HVS
#/weight/high_volt_switch_200epoch5s.pt'
weights_HVS:
  weights: '/weight/HSV/HVS_50epoch_05052023.pt'
  classes: null
  device: 0
  iou_thres: 0.4
  conf_thres: 0.5
  img_size: 640
  max_det: 1000
  agnostic_nms: False
#yolo_belt
weights_belt:
  weights: '/weight/belt/detect_belt.pt'
  classes: null
  device: 0
  iou_thres: 0.4
  conf_thres: 0.5
  img_size: 640
  max_det: 1000
  agnostic_nms: False
#yolo_clock /home/minhssd/AI_hoabinh/weight/I_O/IO_d19m04y2023.pt
weights_clock:
  weights: '/weight/I_O/IO_100epoch_05052023.pt'
  classes: null
  device: 0
  iou_thres: 0.4
  conf_thres: 0.5
  img_size: 640
  max_det: 1000
  agnostic_nms: False

device:
  device: 0
